################## BASE IMAGE ######################
FROM biocontainers/biocontainers:latest

################## METADATA ######################
LABEL base.image="biocontainers:latest"
LABEL version="2"
LABEL software="Samtools"
LABEL software.version="1.3.1"
LABEL about.summary="Tools for manipulating next-generation sequencing data"
LABEL about.home="https://github.com/samtools/samtools"
LABEL about.documentation="https://github.com/samtools/samtools"
LABEL license="https://github.com/samtools/samtools"
LABEL about.tags="Genomics"

USER root

################## MAINTAINER ######################
MAINTAINER GGAnderson <gganderson7@gmail.com>

RUN conda install samtools=1.3.1

WORKDIR /data/

ENTRYPOINT ["samtools"]

CMD ["--help"]